# -- OBSERVAÇÕES -- #

# SUBIR UMA IMAGEM DE UM CONTAINER USANDO PHP COMO BASE COM APACHE
# EXPECIFICANDO A PASTA PADRÃO DO CONTAINER
# QUAIS ARQUIVOS SERÃO COPIADOS PARA A PASTA PADRÃO DO CONTAINER
# INSTALANDO O MYSQLi PARA QUE SEJA REALIZADA A CONEXÃO
#-----------------------------------------------------------------

FROM php:7.4-apache

WORKDIR /var/www/html/

COPY index.php /var/www/html/
COPY conexao.php /var/www/html/

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install mysqli

EXPOSE 80
